#!/bin/sh

#PBS -S /bin/sh
#PBS -N broadcast
#PBS -M myoung44@utk.edu
#PBS -m abe
#PBS -A ACF-UTK0150
#PBS -j oe
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00
#PBS -l qos=condo

module load anaconda3
module load mpi4py

conda activate /nics/b/home/myoung44/env/py

TWELVE=/lustre/haven/proj/UTK0150/yngtodd/src/python/twelve
EXAMPLES=$TWELVE/examples/module_02_mpi
PYMODULE=$EXAMPLES/broadcast.py

mpirun -n 4 python ${PYMODULE}
