#PBS -S /bin/bash
#PBS -A ACF-UTK0150
#PBS -N broadcast
#PBS -M myoung44@utk.edu
#PBS -o job-out.txt
#PBS -e job-err.txt
#PBS -l nodes=1
#PBS -l partition=general:beacon
#PBS -l walltime=00:02:00

module load anaconda3
module load mpi4py

conda activate /nics/b/home/myoung44/env/py

TWELVE=/lustre/haven/proj/UTK0150/yngtodd/src/python/twelve
EXAMPLES=$TWELVE/examples/module_02_mpi
PYMODULE=$EXAMPLES/broadcast.py

mpirun -n 8 python ${PYMODULE}
