#PBS -S /bin/bash
#PBS -A ACF-UTHSC0001
#PBS -m yngtodd
#PBS -M myoung44@utk.edu
#PBS -o $HOME/job_data/job-out.txt
#PBS -e $HOME/job_data/job-err.txt
#PBS -l nodes=1
#PBS -l partition=general:beacon
#PBS -l qos=long
#PBS -l walltime=00:02:00

mdule load anaconda3
conda activate /nics/b/home/myoung44/env/py

cd $PBS_O_WORKDIR

TWELVE=/lustre/haven/proj/UTK0150/yngtodd/src/python/twelve
EXAMPLES=$TWELVE/examples/module_02_mpi
PYMODULE=$EXAMPLES/broadcast.py

mpirun -n 8 python ${PYMODULE}
